name = "media"
title = "多媒体"
suffix_parts = ["ipartment"]

[spliter]
suffix_parts = ["ipartment"]
screenshot_seconds = [10, 20, 30]
count = 5

[[spliters]]
season = 3
count = 2
remove_parts = [[0, 90]]

[[spliters]]
season = 3
episode = 12
count = 3
remove_parts = [[0, 90]]

# =====================
# uploaders
[uploader]
tag = "电视剧,影视剪辑,龙门镖局"

[[uploaders]]
season = 3
tag = "电视剧,影视剪辑,龙门镖局1.5,龙门镖局"

[[uploaders]]
season = 3
episode = 6
dtime = "2025-01-19 11:00:00"

[[marks]]
id = "2-14-1"
title = "断网穿越主线"
parts = ["爱2.14.3", "爱2.14.4"]

[[marks]]
id = "2-14-2"
title = "断网穿越主线"
parts = ["爱2.14.3"]
suffix_parts = ["ipartment", "longmen"]

[[marks]]
id = "path"
title = "断网穿越主线"
path = "examples/data/trailer.mp4"
with_suffix = false
trans_1080p = true
include_segments = [[0, 90]]
exclude_segments = [[0, 90]]
