name = "media"
title = "多媒体"
suffix_parts = ["ipartment"]

[spliter]
suffix_parts = ["ipartment"]
screenshot_seconds = [10, 20, 30]

[[spliters]]
season = 3
episode = 12
remove_parts = [[0, 90]]

[[uploaders]]
season = 3
episode = 6
dtime = "2025-01-19 11:00:00"

[[marks]]
id = "2-14-1"
title = "断网穿越主线"
parts = ["爱2.14.3", "爱2.14.4"]

[[marks]]
id = "2-14-2"
title = "断网穿越主线"
parts = ["爱2.14.3"]
suffix_parts = ["ipartment", "longmen"]
