[package]
name = "bili-video"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
ffmpeg-next = "7.1.0"
lazycmd = "0.1.0"
lazytool = { version = "0.1.0", path = "../../../lazytool" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
